### ISSUE TITLE
Проблема с доступностью скрытых слайдов swiper с клавиатуры

### ISSUE THREAD

**Issue by efiand** [htmlonelove/liga-accelerator-template#43]
Выявлена проблема: при проходе tab'ом с клавиатуры фокус оказывается на слайдах-дубликатах слева от основных, и несколько проходок остаются невидимыми пользователю. Тестировщики закономерно отмечают это как баг.

Выявлено решение - патч стилей `swiper.scss`:

```scss
.swiper-slide-duplicate:not(:not(.swiper-slide-duplicate) ~ .swiper-slide-duplicate) {
  visibility: hidden;
}
```

Оставлю тут, может, будет внесено в сборку или кому-то пригодится.
